name: 'Create Cura packages'
description: 'Create .curapackage files from Cura plugin source repository'
inputs:
  source_folder:  # id of input
    description: 'source folder of the Cura plugin'
    required: true
    default: ''
  plugin_id:  # id of input
    description: 'The Cura plugin id'
    required: false
    default: ''
  package_info_path:  # id of input
    description: 'The package.json file path'
    required: false
    default: ''
outputs:
  packages:
    description: 'List of generated packages'
runs:
  using: 'node20'
  main: 'dist/index.js'
